### ISSUE TITLE
Loading .nkg files is slow for 1000+ functions

### ISSUE THREAD

**Issue by young-x-skyee** [kymata-atlas/kymata-core#271]
When 1000+ functions are contained in an nkg file, it can be very slow to load it.

**Comment by young-x-skyee** [comment]
I tried to make it possible to do this when loading the expression set
```
    elif type_identifier == _ExpressionSetTypeIdentifier.sensor:
        return SensorExpressionSet(
            functions=data_dict[_Keys.functions],
            sensors=[SensorDType(c) for c in data_dict[_Keys.channels][BLOCK_SCALP]],
            latencies=data_dict[_Keys.latencies],
            data=data_dict[_Keys.data][BLOCK_SCALP]
        )
```
which dealt with the problem @caiw suggested. However, it is still very slow to load a large number of functions. For example, I tried to load the expression sets for all the layers (66 layers, each one has one .nkg file containing 1280 functions) in a whisper large model by
```
        # Initialize expression_data
        expression_data = None

        # Loop through the file paths and load the data
        for file_path in tqdm(nkg_files):
            data = load_expression_set(file_path)
            if expression_data is None:
                expression_data = data
            else:
                expression_data += data
```
It seems that it is not very slow when loading the first expression set, but get tremendously slower from the second one onwards

**Comment by neukym** [comment]
This is a great start, thanks Tianyi 👍

**Comment by young-x-skyee** [comment]
Another thing I noticed that may slow things down tremendously is where the addition is defined:

```
    def __add__(self, other: SensorExpressionSet) -> SensorExpressionSet:
        assert array_equal(self.sensors, other.sensors), "Sensors mismatch"
        assert array_equal(self.latencies, other.latencies), "Latencies mismatch"
        # constructor expects a sequence of function names and sequences of 2d matrices
        functions = []
        data = []
        for expr_set in [self, other]:
            for i, function in enumerate(expr_set.functions):
                functions.append(function)
                data.append(expr_set._data[BLOCK_SCALP].data[:, :, i])
        return SensorExpressionSet(
            functions=functions,
            sensors=self.sensors, latencies=self.latencies,
            data=data,
        )
```

I'll have a think about how to improve that as well.

**Comment by neukym** [comment]
Great idea, well done 👍

**Comment by caiw** [comment]
@young-x-skyee Is this fixed on `main`? If you link me to the branch where you've fixed it I can have a look at what might be going wrong with `expression_plot()`.

**Comment by caiw** [comment]
(Reopening temporarily until it's confirmed fixed on `main`)

**Comment by young-x-skyee** [comment]
The branch I fixed it was kymata-language (sorry that I was too busy to reply until now)

**Comment by young-x-skyee** [comment]
You may also see other changes there because I'm also trying to look at #354
