### ISSUE TITLE
Fill in correct values for stimulus drift and shift corrections

### ISSUE THREAD

**Issue by caiw** [kymata-atlas/kymata-core#291]
As mentioned in #290, these fields have been added to config files but aren't yet correct:

- [x] Dataset 3
  - [x] `audio_delivery_latency`
  - [x] `visual_delivery_latency`
  - [x] `tactile_delivery_latency`
  - [x] `audio_delivery_shift_correction`
  - [x] #292
  - [x] `tactile_delivery_shift_correction`
- [x] Dataset 4
  - [x] `audio_delivery_latency`
  - [x] `visual_delivery_latency`
  - [x] `tactile_delivery_latency`
  - [x] `audio_delivery_shift_correction`
  - [ ] `visual_delivery_shift_correction`
  - [x] `tactile_delivery_shift_correction`
- [x] Dataset 4.1
  - [x] `audio_delivery_latency`
  - [x] `visual_delivery_latency`
  - [x] `tactile_delivery_latency`
  - [x] `audio_delivery_shift_correction`
  - [x] `visual_delivery_shift_correction`
  - [x] `tactile_delivery_shift_correction`

## Note to people doing this
stimulus drift can be done using (`trigger == 2`)

**Comment by neukym** [comment]
I added some of these to visual-input-stream.

For tactile, these are set to as `none` as they are not relevant for the current datasets

**Comment by neukym** [comment]
Note that `audio_delivery_shift_correction` is correctly `0.0` for dataset 3 - we have the MISC channel and have confirmed there was no drift (luckily, as I don't think I would have noticed this if there was.).

**Comment by neukym** [comment]
Interestingly, the config for dataset 3 was incorrect anyway, and had the audio and delivery delays from 4, so good job you put this issue here Cai.

**Comment by neukym** [comment]
Completed as part of #290, tested and confirmed to mimic previous results.
