### ISSUE TITLE
Decide on a version-numbering scheme

### ISSUE THREAD

**Issue by caiw** [kymata-atlas/kymata-core#304]
e.g. [semantic versioning](https://semver.org) (@caiw's current preference), or [calendar versioning](https://calver.org)

**Comment by neukym** [comment]
Agree with semantic versioning. Closing.

**Comment by caiw** [comment]
@neukym A related question: when should we update the version number? Every merge to `main`? Or should we have a `dev` branch we usually merge to, and then do periodic merges of that to `main` with version increments?

**Comment by caiw** [comment]
For example we just merged the ippm branch with some new features - arguably warrants a v1.0.1 :)

**Comment by neukym** [comment]
I was just thinking every 6 months or so I would do it manually - so the package will routinely lag main until we have added in enough features that we think it should warrant a new version number. The new features might warrant it, but TBH, I was just planning on doing it every 6 months.

No one uses it as a package at the moment AFAIK so I don't want to be putting strict versioning policies in place. But do you disagree? For instance, do you use the pip package natively?

**Comment by neukym** [comment]
> I was just thinking every 6 months or so I would do it manually 

I don't think we had discussed the mechanism for this actually, now I think about it. So I am versioning main using tagging: Tagging applies a version number to specific git commits on main. (https://github.com/kymata-atlas/kymata-core/releases)

So this can be done in an arbitrary manner, and doesn't have to be linked to a dev branch, or be linked to every commit to main.
