### ISSUE TITLE
Calculating the inverse solution using the fusion method properly

### ISSUE THREAD

**Issue by young-x-skyee** [kymata-atlas/kymata-core#306]
The noise covariance matrices for Russian and English dataset seem to have different structure - the entries dedicated to the EEG and MEG parts are different. How is that information reflected in the fif files and then used properly for noise covariance matrix calculation?

**Comment by young-x-skyee** [comment]
Checked with @neukym that the orders of channels for the English and Russian datasets are different from the very beginning. We need to make sure the ordering is correct for the all the channels when calculating the noise covariance matrix using fusion method.

**Comment by neukym** [comment]
Closed with above fix.
