### ISSUE TITLE
remove `ippm_parameter_evaluation` folder from demos

### ISSUE THREAD

**Issue by neukym** [kymata-atlas/kymata-core#352]
Hi @anirudh1666 and @caiw - I got Kymata to upload automatically to PyPI every time we tag a commit as a release (https://pypi.org/project/kymata/). However, I had to move Anirudh's 2 notebooks to a new folder - `demos/ippm_parameter_evaluation`, otherwise, they are added to the build. (Because they contain lots of PNG's, they would add considerably to the file size if I hadn't moved them.)

But them being in `demos` isn't quite right either as their is already a notebook in here that intends to demonstrate how to create an IPPM from the demo data.

Could you both discuss together how best to handle them? They should perhaps be combined and be relabelled something like `demo_for_automatic_IPPM_evaluation`.

**Comment by caiw** [comment]
I can look at this as part of #225

**Comment by anirudh1666** [comment]
Personally, I think we can keep them locally. The results are out-dated now that we are using the English dataset but the code is still useful for re-usability. You can fix this by deleting them, and I will copy a copy into a different directory before I pull.
