### ISSUE TITLE
70% of CI testing time is spent running `test_download_and_delete_fsaverage_surfaces`

### ISSUE THREAD

**Issue by caiw** [kymata-atlas/kymata-core#360]
This is possibly also violating some TOS of MNE/OSF, if we're downloading multiple MB of data on each run of the CI.

Consider deleting this test?

Or have a separate CI runner which runs once a day/week on a cron job rather than on every commit to a live PR?

**Comment by neukym** [comment]
I added these lines above the tests that involve downloading:

```
@pytest.mark.skipif(
    IN_GITHUB_ACTIONS,
    reason="Test only when run locally - otherwise github will download these each"
    "time we push",
)
```
This skips these tests when using Github actions.

**Comment by neukym** [comment]
Confirmation this is working for all three download tests: (`s` = skip)

<img width="651" alt="Screenshot 2024-08-17 at 19 58 44" src="https://github.com/user-attachments/assets/ff401bb3-1b97-43cf-b20e-f658b0fe43fe">
