### ISSUE TITLE
Config folder is not found since refactor?

### ISSUE THREAD

**Issue by neukym** [kymata-atlas/kymata-core#397]
I'm getting
```
FileNotFoundError: [Errno 2] No such file or directory: '/imaging/projects/cbu/kymata/analyses/andy/kymata-core/kymata/dataset_config/dataset4.yaml'
```
in my trace. I think this is because of the new location of the invokers:

Which means that in invokers/run_gridsearch.py:

```python
if specified_config_file.exists():
        _logger.info(f"Loading config file from {str(specified_config_file)}")
        dataset_config = load_config(str(specified_config_file))
else:
        default_config_file = Path(Path(__file__).parent.parent, "dataset_config", args.config)
        _logger.info(f"Config specified by name. Loading config file from {str(default_config_file)}")
        dataset_config = load_config(str(default_config_file))
        
```
The 5th line is wrong, pointing to the wrong folder? But @caiw, how did you get it to work for the colour analysis if this was wrong?

In any case, presumably the fix should be:
```python
default_config_file = Path(Path(__file__).parent.parent.parent, "dataset_config", args.config)
```
?

**Comment by caiw** [comment]
Ah yes that is almost certainly the issue, sorry.  With the colour analysis I was keeping my own copy of the config file and referring to it directly, thereby taking the first codepath.

**Comment by neukym** [comment]
Perfect - thanks for replying quickly! Fix applied.
